// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbCategoriasHabitaciones
    {
        public tbCategoriasHabitaciones()
        {
            tbHabitaciones = new HashSet<tbHabitaciones>();
        }

        public int CaHa_ID { get; set; }
        public string CaHa_Descripcion { get; set; }
        public int? CaHa_UsuarioCreacion { get; set; }
        public DateTime? CaHa_FechaCreacion { get; set; }
        public int? CaHa_UsuarioModifica { get; set; }
        public DateTime? CaHa_FechaModifica { get; set; }
        public bool? CaHa_Estado { get; set; }

        public virtual tbUsuarios CaHa_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios CaHa_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitaciones { get; set; }
    }
}