// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbColonias = new HashSet<tbColonias>();
            tbDestinosTransportesDsTr_CiudadDestinoNavigation = new HashSet<tbDestinosTransportes>();
            tbDestinosTransportesDsTr_CiudadSalidaNavigation = new HashSet<tbDestinosTransportes>();
        }

        public int Ciud_ID { get; set; }
        public string Ciud_Descripcion { get; set; }
        public int? Pais_ID { get; set; }
        public int? Ciud_UsuarioCreacion { get; set; }
        public DateTime? Ciud_FechaCreacion { get; set; }
        public int? Ciud_UsuarioModifica { get; set; }
        public DateTime? Ciud_FechaModifica { get; set; }
        public bool? Ciud_Estado { get; set; }

        public virtual tbUsuarios Ciud_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Ciud_UsuarioModificaNavigation { get; set; }
        public virtual tbPaises Pais_ { get; set; }
        public virtual ICollection<tbColonias> tbColonias { get; set; }
        public virtual ICollection<tbDestinosTransportes> tbDestinosTransportesDsTr_CiudadDestinoNavigation { get; set; }
        public virtual ICollection<tbDestinosTransportes> tbDestinosTransportesDsTr_CiudadSalidaNavigation { get; set; }
    }
}