// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbColonias
    {
        public tbColonias()
        {
            tbDirecciones = new HashSet<tbDirecciones>();
        }

        public int Colo_ID { get; set; }
        public string Colo_Descripcion { get; set; }
        public int? Ciud_ID { get; set; }
        public int? Colo_UsuarioCreacion { get; set; }
        public DateTime? Colo_FechaCreacion { get; set; }
        public int? Colo_UsuarioModifica { get; set; }
        public DateTime? Colo_FechaModifica { get; set; }
        public bool? Colo_Estado { get; set; }

        public virtual tbCiudades Ciud_ { get; set; }
        public virtual tbUsuarios Colo_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Colo_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbDirecciones> tbDirecciones { get; set; }
    }
}