// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbDetallesTransportes
    {
        public tbDetallesTransportes()
        {
            tbReservacionTransporte = new HashSet<tbReservacionTransporte>();
        }

        public int DeTr_ID { get; set; }
        public int? Tprt_ID { get; set; }
        public int? HoTr_ID { get; set; }
        public int? DeTr_Capacidad { get; set; }
        public decimal? DeTr_Precio { get; set; }
        public string DeTr_Matricula { get; set; }
        public int? DeTr_UsuarioCreacion { get; set; }
        public DateTime? DeTr_FechaCreacion { get; set; }
        public int? DeTr_UsuarioModifica { get; set; }
        public DateTime? DeTr_FechaModifica { get; set; }
        public bool? DeTr_Estado { get; set; }

        public virtual tbUsuarios DeTr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios DeTr_UsuarioModificaNavigation { get; set; }
        public virtual tbHorariosTransportes HoTr { get; set; }
        public virtual tbTransportes Tprt { get; set; }
        public virtual ICollection<tbReservacionTransporte> tbReservacionTransporte { get; set; }
    }
}