// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbDirecciones
    {
        public tbDirecciones()
        {
            tbActividadesExtras = new HashSet<tbActividadesExtras>();
            tbHoteles = new HashSet<tbHoteles>();
            tbRestaurantes = new HashSet<tbRestaurantes>();
            tbTransportes = new HashSet<tbTransportes>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Dire_ID { get; set; }
        public int? Dire_UsuarioCreacion { get; set; }
        public DateTime? Dire_FechaCreacion { get; set; }
        public int? Dire_UsuarioModifica { get; set; }
        public DateTime? Dire_FechaModifica { get; set; }
        public bool? Dire_Estado { get; set; }
        public string Dire_Calle { get; set; }
        public string Dire_Avenida { get; set; }
        public int? Colo_ID { get; set; }

        public virtual tbColonias Colo_ { get; set; }
        public virtual tbUsuarios Dire_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Dire_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbActividadesExtras> tbActividadesExtras { get; set; }
        public virtual ICollection<tbHoteles> tbHoteles { get; set; }
        public virtual ICollection<tbRestaurantes> tbRestaurantes { get; set; }
        public virtual ICollection<tbTransportes> tbTransportes { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}