// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int EsCi_Id { get; set; }
        public string EsCi_Descripcion { get; set; }
        public int? EsCi_UsuarioCreacion { get; set; }
        public DateTime? EsCi_FechaCreacion { get; set; }
        public int? EsCi_UsuarioModifica { get; set; }
        public DateTime? EsCi_FechaModifica { get; set; }
        public bool? EsCi_Estado { get; set; }

        public virtual tbUsuarios EsCi_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios EsCi_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}