// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbHabitaciones
    {
        public tbHabitaciones()
        {
            tbReservacionesDetalles = new HashSet<tbReservacionesDetalles>();
        }

        public int Habi_ID { get; set; }
        public string Habi_Nombre { get; set; }
        public string Habi_Descripcion { get; set; }
        public int? CaHa_ID { get; set; }
        public int? Hote_ID { get; set; }
        public decimal? Habi_Precio { get; set; }
        public int? Habi_UsuarioCreacion { get; set; }
        public DateTime? Habi_FechaCreacion { get; set; }
        public int? Habi_UsuarioModifica { get; set; }
        public DateTime? Habi_FechaModifica { get; set; }
        public bool? Habi_Estado { get; set; }

        public virtual tbCategoriasHabitaciones CaHa { get; set; }
        public virtual tbUsuarios Habi_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Habi_UsuarioModificaNavigation { get; set; }
        public virtual tbHoteles Hote { get; set; }
        public virtual ICollection<tbReservacionesDetalles> tbReservacionesDetalles { get; set; }
    }
}