// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbHotelesMenus
    {
        public int HoMe_ID { get; set; }
        public string HoMe_Descripcion { get; set; }
        public decimal? HoMe_Precio { get; set; }
        public int? Hote_ID { get; set; }
        public int? Time_ID { get; set; }
        public int? HoMe_UsuarioCreacion { get; set; }
        public DateTime? HoMe_FechaCreacion { get; set; }
        public int? HoMe_UsuarioModifica { get; set; }
        public DateTime? HoMe_FechaModifica { get; set; }
        public bool? HoMe_Estado { get; set; }

        public virtual tbUsuarios HoMe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios HoMe_UsuarioModificaNavigation { get; set; }
        public virtual tbHoteles Hote { get; set; }
        public virtual tbTipoMenus Time { get; set; }
    }
}