// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbHotelesActividades
    {
        public tbHotelesActividades()
        {
            tbReservacionesActividadesHoteles = new HashSet<tbReservacionesActividadesHoteles>();
        }

        public int HoAc_ID { get; set; }
        public int? Actv_ID { get; set; }
        public string HoAc_Descripcion { get; set; }
        public decimal? HoAc_Precio { get; set; }
        public int? Hote_ID { get; set; }
        public int? HoAc_UsuarioCreacion { get; set; }
        public DateTime? HoAc_FechaCreacion { get; set; }
        public int? HoAc_UsuarioModifica { get; set; }
        public DateTime? HoAc_FechaModifica { get; set; }
        public bool? HoAc_Estado { get; set; }

        public virtual tbActividades Actv_ { get; set; }
        public virtual tbUsuarios HoAc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios HoAc_UsuarioModificaNavigation { get; set; }
        public virtual tbHoteles Hote_ { get; set; }
        public virtual ICollection<tbReservacionesActividadesHoteles> tbReservacionesActividadesHoteles { get; set; }
    }
}