// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbHorariosTransportes
    {
        public tbHorariosTransportes()
        {
            tbDetallesTransportes = new HashSet<tbDetallesTransportes>();
        }

        public int HoTr_ID { get; set; }
        public int? DsTr_ID { get; set; }
        public DateTime? HoTr_Fecha { get; set; }
        public string HoTr_HoraSalida { get; set; }
        public string HoTr_HoraLlegada { get; set; }
        public int? HoTr_UsuarioCreacion { get; set; }
        public DateTime? HoTr_FechaCreacion { get; set; }
        public int? HoTr_UsuarioModifica { get; set; }
        public DateTime? HoTr_FechaModifica { get; set; }
        public bool? HoTr_Estado { get; set; }
        public int? Partner_ID { get; set; }

        public virtual tbDestinosTransportes DsTr_ { get; set; }
        public virtual tbUsuarios HoTr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios HoTr_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbDetallesTransportes> tbDetallesTransportes { get; set; }
    }
}