// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tblGruposElementosNavbar
    {
        public tblGruposElementosNavbar()
        {
            tbPermisos = new HashSet<tbPermisos>();
        }

        public int GrEN_Id { get; set; }
        public string GrEN_NombreGrupo { get; set; }
        public bool? GrEN_Estado { get; set; }

        public virtual ICollection<tbPermisos> tbPermisos { get; set; }
    }
}