// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbMenus
    {
        public int Menu_ID { get; set; }
        public int? Time_ID { get; set; }
        public string Menu_Descripcion { get; set; }
        public string Menu_Nombre { get; set; }
        public decimal? Menu_Precio { get; set; }
        public int? Rest_ID { get; set; }
        public int? Menu_UsuarioCreacion { get; set; }
        public DateTime? Menu_FechaCreacion { get; set; }
        public int? Menu_UsuarioModifica { get; set; }
        public DateTime? Menu_FechaModifica { get; set; }
        public bool? Menu_Estado { get; set; }

        public virtual tbUsuarios Menu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Menu_UsuarioModificaNavigation { get; set; }
        public virtual tbRestaurantes Rest_ { get; set; }
        public virtual tbTipoMenus Time_ { get; set; }
    }
}