// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbModulos
    {
        public tbModulos()
        {
            tbPermisos = new HashSet<tbPermisos>();
        }

        public int Modu_Id { get; set; }
        public string Modu_Descripcion { get; set; }
        public bool? Modu_Estado { get; set; }

        public virtual ICollection<tbPermisos> tbPermisos { get; set; }
    }
}