// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbModulos
    {
        public int Modu_Id { get; set; }
        public string Modu_Descripcion { get; set; }
        public bool? Modu_Estado { get; set; }
        public int? Modu_UsuarioCreacion { get; set; }
        public DateTime? Modu_FechaCreacion { get; set; }
        public int? Modu_UsuarioModifica { get; set; }
        public DateTime? Modu_FechaModifica { get; set; }
    }
}