// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbPartners
    {
        public tbPartners()
        {
            tbActividadesExtras = new HashSet<tbActividadesExtras>();
            tbHoteles = new HashSet<tbHoteles>();
            tbTransportes = new HashSet<tbTransportes>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Part_ID { get; set; }
        public string Part_Nombre { get; set; }
        public string Part_Email { get; set; }
        public string Part_Telefono { get; set; }
        public int? TiPart_Id { get; set; }
        public int? Part_UsuarioCreacion { get; set; }
        public DateTime? Part_FechaCreacion { get; set; }
        public int? Part_UsuarioModifica { get; set; }
        public DateTime? Part_FechaModifica { get; set; }
        public bool? Part_Estado { get; set; }
        public string Part_Url { get; set; }

        public virtual tbUsuarios Part_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Part_UsuarioModificaNavigation { get; set; }
        public virtual tbTipoPartners TiPart_ { get; set; }
        public virtual ICollection<tbActividadesExtras> tbActividadesExtras { get; set; }
        public virtual ICollection<tbHoteles> tbHoteles { get; set; }
        public virtual ICollection<tbTransportes> tbTransportes { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}