// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbPaquetePredeterminadosActividadesHoteles
    {
        public int PaAc_ID { get; set; }
        public int? Paqu_ID { get; set; }
        public int? HoAc_ID { get; set; }
        public int? PaAc_CantidadPersonas { get; set; }
        public int? PaAc_UsuarioCreacion { get; set; }
        public DateTime? PaAc_FechaCreacion { get; set; }
        public int? PaAc_UsuarioModifica { get; set; }
        public DateTime? PaAc_FechaModifica { get; set; }
        public bool? PaAc_Estado { get; set; }

        public virtual tbHotelesActividades HoAc_ { get; set; }
        public virtual tbUsuarios PaAc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios PaAc_UsuarioModificaNavigation { get; set; }
        public virtual tbPaquetePredeterminados Paqu_ { get; set; }
    }
}