// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbPaquetesHabitaciones
    {
        public int PaHa_Id { get; set; }
        public int? Paqu_Id { get; set; }
        public int? Habi_Id { get; set; }
        public int? PaHa_UsuarioCreacion { get; set; }
        public DateTime? PaHa_FechaCreacion { get; set; }
        public int? PaHa_UsuarioModifica { get; set; }
        public DateTime? PaHa_FechaModifica { get; set; }
        public bool? PaHa_Estado { get; set; }

        public virtual tbHabitaciones Habi { get; set; }
        public virtual tbUsuarios PaHa_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios PaHa_UsuarioModificaNavigation { get; set; }
        public virtual tbPaquetePredeterminados Paqu { get; set; }
    }
}