// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public int Pais_ID { get; set; }
        public string Pais_Codigo { get; set; }
        public string Pais_Descripcion { get; set; }
        public string Pais_Nacionalidad { get; set; }
        public int? Pais_UsuarioCreacion { get; set; }
        public DateTime? Pais_FechaCreacion { get; set; }
        public int? Pais_UsuarioModifica { get; set; }
        public DateTime? Pais_FechaModifica { get; set; }
        public bool? Pais_Estado { get; set; }
        public string Pais_ISO { get; set; }

        public virtual tbUsuarios Pais_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Pais_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}