// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbPermisos
    {
        public int Perm_ID { get; set; }
        public string Perm_Icono { get; set; }
        public string Perm_Descripcion { get; set; }
        public string Perm_Controlador { get; set; }
        public string Perm_Action { get; set; }
        public int? Modu_ID { get; set; }
        public bool? Perm_esVisible { get; set; }
        public int? Perm_UsuarioCreacion { get; set; }
        public DateTime? Perm_FechaCreacion { get; set; }
        public int? Perm_UsuarioModifica { get; set; }
        public DateTime? Perm_FechaModifica { get; set; }
        public bool? Perm_Estado { get; set; }

        public virtual tbUsuarios Perm_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Perm_UsuarioModificaNavigation { get; set; }
    }
}