// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbRestaurantes
    {
        public tbRestaurantes()
        {
            tbMenus = new HashSet<tbMenus>();
            tbPaquetePredeterminados = new HashSet<tbPaquetePredeterminados>();
            tbReservacionRestaurantes = new HashSet<tbReservacionRestaurantes>();
        }

        public int Rest_ID { get; set; }
        public int? Dire_ID { get; set; }
        public string Rest_Nombre { get; set; }
        public int? Part_ID { get; set; }
        public int? Rest_UsuarioCreacion { get; set; }
        public DateTime? Rest_FechaCreacion { get; set; }
        public int? Rest_UsuarioModifica { get; set; }
        public DateTime? Rest_FechaModifica { get; set; }
        public bool? Rest_Estado { get; set; }

        public virtual tbDirecciones Dire { get; set; }
        public virtual tbPartners Part { get; set; }
        public virtual tbUsuarios Rest_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Rest_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbMenus> tbMenus { get; set; }
        public virtual ICollection<tbPaquetePredeterminados> tbPaquetePredeterminados { get; set; }
        public virtual ICollection<tbReservacionRestaurantes> tbReservacionRestaurantes { get; set; }
    }
}