// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbRegistrosPagos
    {
        public int RePa_ID { get; set; }
        public int? Resv_ID { get; set; }
        public int? TiPa_ID { get; set; }
        public decimal? RePa_Monto { get; set; }
        public DateTime? RePa_FechaPago { get; set; }
        public int? RePa_UsuarioCreacion { get; set; }
        public DateTime? RePa_FechaCreacion { get; set; }
        public int? RePa_UsuarioModifica { get; set; }
        public DateTime? RePa_FechaModifica { get; set; }
        public bool? RePa_Estado { get; set; }

        public virtual tbUsuarios RePa_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios RePa_UsuarioModificaNavigation { get; set; }
        public virtual tbReservaciones Resv { get; set; }
        public virtual tbTiposPagos TiPa { get; set; }
    }
}