// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservaciones
    {
        public tbReservaciones()
        {
            tbRegistrosPagos = new HashSet<tbRegistrosPagos>();
            tbReservacionRestaurantes = new HashSet<tbReservacionRestaurantes>();
            tbReservacionTransporte = new HashSet<tbReservacionTransporte>();
            tbReservacionesActividadesExtras = new HashSet<tbReservacionesActividadesExtras>();
            tbReservacionesActividadesHoteles = new HashSet<tbReservacionesActividadesHoteles>();
            tbReservacionesHoteles = new HashSet<tbReservacionesHoteles>();
        }

        public int Resv_ID { get; set; }
        public int? Usua_ID { get; set; }
        public int? Paqu_ID { get; set; }
        public bool? Resv_esPersonalizado { get; set; }
        public int? Resv_NumeroPersonas { get; set; }
        public bool? Resv_ConfirmacionPago { get; set; }
        public bool? Resv_ConfirmacionHotel { get; set; }
        public bool? Resv_ConfirmacionRestaurante { get; set; }
        public bool? Resv_ConfirmacionTrans { get; set; }
        public decimal? Resv_Precio { get; set; }
        public int? Resv_UsuarioCreacion { get; set; }
        public DateTime? Resv_FechaCreacion { get; set; }
        public int? Resv_UsuarioModifica { get; set; }
        public DateTime? Resv_FechaModifica { get; set; }
        public bool? Resv_Estado { get; set; }

        public virtual tbPaquetePredeterminados Paqu { get; set; }
        public virtual tbUsuarios Resv_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Resv_UsuarioModificaNavigation { get; set; }
        public virtual tbUsuarios Usua { get; set; }
        public virtual ICollection<tbRegistrosPagos> tbRegistrosPagos { get; set; }
        public virtual ICollection<tbReservacionRestaurantes> tbReservacionRestaurantes { get; set; }
        public virtual ICollection<tbReservacionTransporte> tbReservacionTransporte { get; set; }
        public virtual ICollection<tbReservacionesActividadesExtras> tbReservacionesActividadesExtras { get; set; }
        public virtual ICollection<tbReservacionesActividadesHoteles> tbReservacionesActividadesHoteles { get; set; }
        public virtual ICollection<tbReservacionesHoteles> tbReservacionesHoteles { get; set; }
    }
}