// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservacionTransporte
    {
        public int ReTr_ID { get; set; }
        public int? Detr_ID { get; set; }
        public int? Resv_ID { get; set; }
        public int? ReTr_CantidadAsientos { get; set; }
        public bool? ReTr_Cancelado { get; set; }
        public DateTime? ReTr_FechaCancelado { get; set; }
        public int? ReTr_UsuarioCreacion { get; set; }
        public DateTime? ReTr_FechaCreacion { get; set; }
        public int? ReTr_UsuarioModifica { get; set; }
        public DateTime? ReTr_FechaModifica { get; set; }
        public bool? ReTr_Estado { get; set; }

        public virtual tbDetallesTransportes Detr_ { get; set; }
        public virtual tbUsuarios ReTr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ReTr_UsuarioModificaNavigation { get; set; }
        public virtual tbReservaciones Resv_ { get; set; }
    }
}