// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservacionesHoteles
    {
        public tbReservacionesHoteles()
        {
            tbReservacionesDetalles = new HashSet<tbReservacionesDetalles>();
        }

        public int ReHo_ID { get; set; }
        public DateTime? ReHo_FechaEntrada { get; set; }
        public DateTime? ReHo_FechaSalida { get; set; }
        public int? Resv_ID { get; set; }
        public decimal? ReHo_PrecioTotal { get; set; }
        public int? ReHo_UsuarioCreacion { get; set; }
        public DateTime? ReHo_FechaCreacion { get; set; }
        public int? ReHo_UsuarioModifica { get; set; }
        public DateTime? ReHo_FechaModifica { get; set; }
        public bool? ReHo_Estado { get; set; }

        public virtual tbUsuarios ReHo_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ReHo_UsuarioModificaNavigation { get; set; }
        public virtual tbReservaciones Resv { get; set; }
        public virtual ICollection<tbReservacionesDetalles> tbReservacionesDetalles { get; set; }
    }
}