// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservacionRestaurantes
    {
        public int ReRe_ID { get; set; }
        public int? Resv_ID { get; set; }
        public int? Rest_ID { get; set; }
        public DateTime? ReRe_FechaReservacion { get; set; }
        public string ReRe_HoraReservacion { get; set; }
        public int? ReRe_UsuarioCreacion { get; set; }
        public DateTime? ReRe_FechaCreacion { get; set; }
        public int? ReRe_UsuarioModifica { get; set; }
        public DateTime? ReRe_FechaModifica { get; set; }
        public bool? ReRe_Estado { get; set; }

        public virtual tbUsuarios ReRe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ReRe_UsuarioModificaNavigation { get; set; }
        public virtual tbRestaurantes Rest_ { get; set; }
        public virtual tbReservaciones Resv_ { get; set; }
    }
}