// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservacionesActividadesHoteles
    {
        public int ReAH_ID { get; set; }
        public int? Resv_ID { get; set; }
        public int? HoAc_ID { get; set; }
        public int? ReAH_Cantidad { get; set; }
        public DateTime? ReAH_FechaReservacion { get; set; }
        public string ReAH_HoraReservacion { get; set; }
        public int? ReAH_UsuarioCreacion { get; set; }
        public DateTime? ReAH_FechaCreacion { get; set; }
        public int? ReAH_UsuarioModifica { get; set; }
        public DateTime? ReAH_FechaModifica { get; set; }
        public bool? ReAH_Estado { get; set; }

        public virtual tbHotelesActividades HoAc_ { get; set; }
        public virtual tbUsuarios ReAH_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ReAH_UsuarioModificaNavigation { get; set; }
        public virtual tbReservaciones Resv_ { get; set; }
    }
}