// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbReservacionesDetalles
    {
        public int ReDe_ID { get; set; }
        public int? Habi_ID { get; set; }
        public int? ReHo_ID { get; set; }
        public int? ReDe_UsuarioCreacion { get; set; }
        public DateTime? ReDe_FechaCreacion { get; set; }
        public int? ReDe_UsuarioModifica { get; set; }
        public DateTime? ReDe_FechaModifica { get; set; }
        public bool? ReDe_Estado { get; set; }

        public virtual tbHabitaciones Habi { get; set; }
        public virtual tbUsuarios ReDe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios ReDe_UsuarioModificaNavigation { get; set; }
        public virtual tbReservacionesHoteles ReHo { get; set; }
    }
}