// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbTipoPartners = new HashSet<tbTipoPartners>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Role_ID { get; set; }
        public string Role_Descripcion { get; set; }
        public int? Role_UsuarioCreacion { get; set; }
        public DateTime? Role_FechaCreacion { get; set; }
        public int? Role_UsuarioModifica { get; set; }
        public DateTime? Role_FechaModifica { get; set; }
        public bool? Role_Estado { get; set; }

        public virtual tbUsuarios Role_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Role_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbTipoPartners> tbTipoPartners { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}