// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbRolesPermisos
    {
        public int RoPe_ID { get; set; }
        public int? Perm_ID { get; set; }
        public int? Role_ID { get; set; }
        public int? RoPe_UsuarioCreacion { get; set; }
        public DateTime? RoPe_FechaCreacion { get; set; }
        public int? RoPe_UsuarioModifica { get; set; }
        public DateTime? RoPe_FechaModifica { get; set; }
        public bool? RoPe_Estado { get; set; }

        public virtual tbUsuarios RoPe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios RoPe_UsuarioModificaNavigation { get; set; }
    }
}