// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbTipoMenus
    {
        public tbTipoMenus()
        {
            tbHotelesMenus = new HashSet<tbHotelesMenus>();
            tbMenus = new HashSet<tbMenus>();
        }

        public int Time_ID { get; set; }
        public string Time_Descripcion { get; set; }
        public int? Time_UsuarioCreacion { get; set; }
        public DateTime? Time_FechaCreacion { get; set; }
        public int? Time_UsuarioModifica { get; set; }
        public DateTime? Time_FechaModifica { get; set; }
        public bool? Time_Estado { get; set; }

        public virtual tbUsuarios Time_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Time_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbHotelesMenus> tbHotelesMenus { get; set; }
        public virtual ICollection<tbMenus> tbMenus { get; set; }
    }
}