// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbTiposActividades
    {
        public tbTiposActividades()
        {
            tbActividades = new HashSet<tbActividades>();
        }

        public int TiAc_ID { get; set; }
        public string TiAc_Descripcion { get; set; }
        public int? TiAc_UsuarioCreacion { get; set; }
        public DateTime? TiAc_FechaCreacion { get; set; }
        public int? TiAc_UsuarioModifica { get; set; }
        public DateTime? TiAc_FechaModifica { get; set; }
        public bool? TiAc_Estado { get; set; }

        public virtual tbUsuarios TiAc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios TiAc_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividades { get; set; }
    }
}