// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class tbTipoPartners
    {
        public tbTipoPartners()
        {
            tbPartners = new HashSet<tbPartners>();
        }

        public int TiPar_Id { get; set; }
        public string TiPar_Descripcion { get; set; }
        public int? Rol_Id { get; set; }
        public int? TiPar_UsuarioCreacion { get; set; }
        public DateTime? TiPar_FechaCreacion { get; set; }
        public int? TiPar_UsuarioModifica { get; set; }
        public DateTime? TiPar_FechaModifica { get; set; }
        public bool? TiPar_Estado { get; set; }

        public virtual tbRoles Rol_ { get; set; }
        public virtual tbUsuarios TiPar_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios TiPar_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbPartners> tbPartners { get; set; }
    }
}