// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbHoteles
    {
        public int ID { get; set; }
        public string Hotel { get; set; }
        public string Descripcion { get; set; }
        public int CiudadID { get; set; }
        public string Ciudad { get; set; }
        public int ID_Direc { get; set; }
        public int ColoniaID { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string Avenida { get; set; }
        public int ID_Partner { get; set; }
        public string Partners { get; set; }
        public string Image_URL { get; set; }
        public int ID_UsuaCrea { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? ID_UsuaModifica { get; set; }
        public string UsuarioModifica { get; set; }
        public DateTime? FechaModifica { get; set; }
        public bool? Estado { get; set; }
    }
}