// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tblGruposElementosNavbar
    {
        public int ID { get; set; }
        public string nombre_grupo { get; set; }
    }
}