// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbHotelesActividades
    {
        public int ID { get; set; }
        public string Actividad { get; set; }
        public string Descripcion { get; set; }
        public decimal? Precio { get; set; }
        public string Hotel { get; set; }
        public string Image_URL { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string UsuarioModifica { get; set; }
        public DateTime? FechaModifica { get; set; }
        public bool? Estado { get; set; }
    }
}