// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbPaquetePredeterminadosActividadesHoteles
    {
        public int ID { get; set; }
        public int ID_Paque { get; set; }
        public string Paquete { get; set; }
        public string Descripcion_Paquete { get; set; }
        public int ID_HoAc { get; set; }
        public string Descripcion_HotelActv { get; set; }
        public int? ID_Actividad { get; set; }
        public string Actividad { get; set; }
    }
}