// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbPaquetesHabitaciones
    {
        public int ID { get; set; }
        public int? Paquete_Id { get; set; }
        public string Nombre_Hotel { get; set; }
        public string Hotel_Descripcion { get; set; }
        public int? Habitacion_Id { get; set; }
        public string Habitacion_Nombre { get; set; }
        public string Habitacion_Descripcion { get; set; }
        public int? Habitacion_Capacidad { get; set; }
        public decimal? Habitacion_Precio { get; set; }
        public int Categoria_Habitacion_Id { get; set; }
        public string Categoria_Habitacion { get; set; }
    }
}