// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbReservacionesDetalles
    {
        public int ID { get; set; }
        public string Nombre_Habitacion { get; set; }
        public string Descripcion_Habitacion { get; set; }
        public string Categoria_Habitacion { get; set; }
        public string Hotel { get; set; }
        public decimal? Precio_Habitacion { get; set; }
        public DateTime? Fecha_Entrada { get; set; }
        public DateTime? Fecha_Salida { get; set; }
        public decimal? Precio_ReservacionHotel { get; set; }
        public string Usuario_Creacion { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public string Usuario_Modifica { get; set; }
        public DateTime? Fecha_Modifica { get; set; }
        public bool? Estado { get; set; }
    }
}