// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbReservacionTransporteCompleto
    {
        public int Id { get; set; }
        public int Id_Transportes { get; set; }
        public int Reservacion { get; set; }
        public int Id_Cliente { get; set; }
        public string Cliente { get; set; }
        public int? Asientos { get; set; }
        public bool? Cancelado { get; set; }
        public DateTime? Fecha_Cancelado { get; set; }
        public int ID_detalle_Transporte { get; set; }
        public string Tipo_Transporte { get; set; }
        public int Partner_ID { get; set; }
        public string Partner_Nombre { get; set; }
        public DateTime? Transporte_FechaSalida { get; set; }
        public string Hora_Salida { get; set; }
        public string Hora_Llegada { get; set; }
        public int? Capacidad { get; set; }
        public decimal? Precio { get; set; }
        public int ID_Usuario_Creacion { get; set; }
        public string Usuario_Creacion { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public int? ID_Usuario_Modifica { get; set; }
        public string Usuario_Modifica { get; set; }
        public DateTime? Fecha_Modifica { get; set; }
        public bool? Estado { get; set; }
    }
}