// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbActividadesExtras
    {
        public int ID { get; set; }
        public int ID_Partner { get; set; }
        public string Partner { get; set; }
        public int ID_Actividad { get; set; }
        public string Actividad { get; set; }
        public decimal? Precio { get; set; }
        public string Descripcion { get; set; }
        public int? ID_Crea { get; set; }
        public string ImageURL { get; set; }
        public string UsuarioCrea { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? ID_Modifica { get; set; }
        public string UsuarioModifica { get; set; }
        public DateTime? FechaModifica { get; set; }
        public bool? Estado { get; set; }
    }
}