// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbReservacionRestaurante
    {
        public int Id { get; set; }
        public int Resv_ID { get; set; }
        public string Cliente { get; set; }
        public int ID_Restaurante { get; set; }
        public string Restaurante { get; set; }
        public int? ID_Parter { get; set; }
        public string Partner_Nombre { get; set; }
        public DateTime? Fecha_Reservacion { get; set; }
        public string Hora_Reservacion { get; set; }
        public bool? ConfirmacionReservacion { get; set; }
        public int ID_Usuario_Creacion { get; set; }
        public string Usuario_Creacion { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public int? ID_Usuario_Modifica { get; set; }
        public string Usuario_Modifica { get; set; }
        public DateTime? Fecha_Modifica { get; set; }
        public bool? Estado { get; set; }
    }
}