// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbTipoPartners
    {
        public int? ID { get; set; }
        public string Descripcion { get; set; }
        public int? Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public int? Usuario_Creacion_Id { get; set; }
        public string Usuario_Creacion_Nombre { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public int? Usuario_Modifica_Id { get; set; }
        public string Usuario_Modifica_Nombre { get; set; }
        public int? Fecha_Modifica { get; set; }
    }
}