// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbDestinosTransportes
    {
        public int ID { get; set; }
        public string CiudadSalida { get; set; }
        public int CiudadSalidaID { get; set; }
        public int PaisSalidaID { get; set; }
        public string PaisSalida { get; set; }
        public string CiudadDestino { get; set; }
        public int CiudadDestinoID { get; set; }
        public int PaisDestinoID { get; set; }
        public string PaisDestino { get; set; }
        public int? Partner_ID { get; set; }
        public int? UsuarioCreacion { get; set; }
        public string UsuarioCreacionID { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public int? UsuarioModifica { get; set; }
        public string UsuarioModificaID { get; set; }
        public DateTime? FechaModifica { get; set; }
        public bool? Estado { get; set; }
    }
}