// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Total.Travel.Entities.Entities
{
    public partial class VW_tbReservacionTransporte
    {
        public int Id { get; set; }
        public int? Capacidad { get; set; }
        public decimal? Precio { get; set; }
        public int? Reservacion { get; set; }
        public int? Asientos { get; set; }
        public bool? Cancelado { get; set; }
        public DateTime? Fecha_Cancelado { get; set; }
        public string Usuario_Creacion { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public string Usuario_Modifica { get; set; }
        public DateTime? Fecha_Modifica { get; set; }
        public bool? Estado { get; set; }
    }
}